# Generated by Django 4.2 on 2023-06-25 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_reputation_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile',
            new_name='profile_picture',
        ),
    ]
